# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "wagon-erpify"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rapha\u{eb}l Valyi"]
  s.date = "2013-12-27"
  s.description = "Allows to use OpenERP via erpify in local LocomotiveCMS sites developped with wagon"
  s.email = "rvalyi@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/wagon-erpify.rb",
    "test/helper.rb",
    "test/test_wagon-erpify.rb",
    "wagon-erpify.gemspec"
  ]
  s.homepage = "http://github.com/akretion/wagon-erpify"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "enable OpenERP in LocomotiveCMS sites developped with wagon"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<locomotivecms_wagon>, [">= 0"])
    else
      s.add_dependency(%q<locomotivecms_wagon>, [">= 0"])
    end
  else
    s.add_dependency(%q<locomotivecms_wagon>, [">= 0"])
  end
end

